import mongoose from 'mongoose';

const blogSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    slug: { type: String, required: true, unique: true },
    excerpt: String,
    content: { type: String, required: true },
    featuredImage: String,
    ogImage: String,
    featuredImagePrompt: String,
    imageAlt: String,
    ogImageAlt: String,
    authorImage: String,
    editorImages: [String],
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
    categoryName: String,
    tags: [String],
    secondaryKeywords: [String],
    focusKeyword: String,
    status: { type: String, enum: ['draft', 'ai-generated', 'published', 'scheduled', 'archived'], default: 'draft' },
    source: { type: String, enum: ['admin', 'trend-draft'], default: 'admin' },
    seoTitle: String,
    seoDescription: String,
    canonicalUrl: String,
    schemaType: { type: String, enum: ['Article', 'BlogPosting', 'NewsArticle', 'TechArticle', 'FAQPage'], default: 'BlogPosting' },
    faqs: [{ question: String, answer: String }],
    authorName: String,
    internalLinks: [String],
    externalLinks: [String],
    readTime: Number,
    seoScore: { type: Number, default: 0 },
    seoChecks: [{ label: String, status: String, message: String }],
    geoTitle: String,
    geoSummary: String,
    geoAnswer: String,
    geoAudience: String,
    geoRegion: String,
    geoEntities: [String],
    geoQuestions: [String],
    geoSources: [String],
    geoScore: { type: Number, default: 0 },
    geoChecks: [{ label: String, status: String, message: String }],
    views: { type: Number, default: 0 },
    clicks: { type: Number, default: 0 },
    ctr: { type: Number, default: 0 },
    bounceRate: { type: Number, default: 0 },
    topKeywords: [String],
    trafficSources: [{ source: String, count: Number }],
    scheduledAt: Date,
    publishedAt: Date
  },
  { timestamps: true }
);

export const Blog = mongoose.model('Blog', blogSchema);
